### PR TITLE
PR393 help updates

### PR DESCRIPTION
**Pull request by ederag**
These updates should complete nicely your PR https://github.com/projecthamster/hamster/pull/393.
Could you please review them ?

### CODE REVIEW

**Review by mwilck — COMMENTED** [review]
Yet another app that provides instructions for basically every OS out there except openSUSE :-/
But yeah, fine.

**Review by mwilck — CHANGES_REQUESTED** [review]
I don't recommend to refer to bugs or issues in the help pages. It's distracting and alerts users of bugs they might not even notice otherwise. Also, you're likely to forget to remove the remark once the error is fixed.

Describe the behavior how it *should be*, and fix the bug.

**Review by mwilck — CHANGES_REQUESTED** [review]
Again, don't point out bugs in the help pages.

**Review by mwilck — COMMENTED** [review]
Why do you create two separate single-paragraph notes for this? Isn't a "relative time" just another fom of "time input"? I'd prefer just a single paragraph, without "note", explaining the different ways to enter times.

**Comment by ederag** [comment]
Thanks for reviewing.

> Yet another app that provides instructions for basically every OS out there except openSUSE :-/
> But yeah, fine.

I really like openSUSE, so of course in the [README](https://github.com/projecthamster/hamster/blob/master/README.md#dependencies) there *is* the relevant installation line, as for other distros:

> openSUSE Leap-15: `zypper install intltool python3-pyxdg python3-cairo python3-gobject-Gdk`

Is anything else missing ?


> I don't recommend to refer to bugs or issues in the help pages. It's distracting and alerts users of bugs they might not even notice otherwise. Also, you're likely to forget to remove the remark once the error is fixed.
> 
> Describe the behavior how it _should be_, and fix the bug.

In principle I totally agree.
Here is why I did that this time:
1) Changing the help files would make users learn the wrong behavior,
then adapt again when the bug is fixed.
With the issue mentioned, the users know that it is temporary.
2) I deliberately listed the help lines in the relevant issues. This way I'll remember to change them once fixed.
3) Some of those bugs will require a lot of care. There is no way to fix them in this PR. Not even sure they can be fixed before the next version.

I'm still open to think about it.
Or do that alleviate your objections ?

> Why do you create two separate single-paragraph notes for this? Isn't a "relative time" just another form of "time input"? I'd prefer just a single paragraph, without "note", explaining the different ways to enter times.

I would leave the *nota bene* because those are easily missed, and worth the emphasis in my opinion.
But you are right that they should be together,
just in a list to clearly show that those are related but clearly different informations.
Done in 6155d332ee398b278bef42a6f6479cee3d51326f

Thanks again for the review.

**Comment by mwilck** [comment]
> > Yet another app that provides instructions for basically every OS out there except openSUSE :-/
> > But yeah, fine.
> 
> I really like openSUSE, so of course in the [README](https://github.com/projecthamster/hamster/blob/master/README.md#dependencies) there _is_ the relevant installation line, as for other distros:

I was referring to sqlitebrowser, not hamster.

I'm fine with your answers. Is this ready to merge now, or is there more to come?

**Comment by ederag** [comment]
> I was referring to sqlitebrowser, not hamster.

It's mainly up to us openSUSE users.
PR filed: https://github.com/sqlitebrowser/sqlitebrowser/pull/1792
Most of the time I do not care because `cnf` is really powerful.

> I'm fine with your answers. Is this ready to merge now, or is there more to come?

Thanks, I'm glad ! Done then.

**Pull request merged**
